version: '3.3'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile

    image: svc-jenkins

    ports:
      - "8080:8080"
      - "50000:50000" # port for executor nodes

    volumes:
     - /home/jenkins/svc-jenkins:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
